#!/bin/sh
stagedFiles=$(git diff --staged --name-only)
echo "Running spotlessApply. Formatting code..."
export JAVA_HOME=$HOME'/wpilib/2022/jdk'
./gradlew spotlessApply --daemon
# Part 3
for file in $stagedFiles; do
  if test -f "$file"; then
    git add "$file"
  fi
done